### ISSUE TITLE
ReferenceError: btoa is not defined

### ISSUE THREAD

**Issue by toshiboy86** [torusresearch/torus-embed#150]
**Describe the bug**
`const Torus = require("@toruslabs/torus-embed");`

returns 
```
Thrown:
ReferenceError: btoa is not defined
    at Object.<anonymous> (/Users/user/Workplace/project/torus-sdk-js/node_modules/@toruslabs/fetch-node-details/dist/fetchNodeDetails.cjs.js:16:17658)
    at Object.module.exports (/Users/user/Workplace/project/torus-sdk-js/node_modules/@toruslabs/fetch-node-details/dist/fetchNodeDetails.cjs.js:16:21457)
    at r (/Users/user/Workplace/project/torus-sdk-js/node_modules/@toruslabs/fetch-node-details/dist/fetchNodeDetails.cjs.js:1:124)
    at Object.module.exports (/Users/user/Workplace/project/torus-sdk-js/node_modules/@toruslabs/fetch-node-details/dist/fetchNodeDetails.cjs.js:8:175021)
    at r (/Users/user/Workplace/project/torus-sdk-js/node_modules/@toruslabs/fetch-node-details/dist/fetchNodeDetails.cjs.js:1:124)
    at Object.module.exports (/Users/user/Workplace/project/torus-sdk-js/node_modules/@toruslabs/fetch-node-details/dist/fetchNodeDetails.cjs.js:8:173909)
    at r (/Users/user/Workplace/project/torus-sdk-js/node_modules/@toruslabs/fetch-node-details/dist/fetchNodeDetails.cjs.js:1:124)
    at Object.module.exports (/Users/user/Workplace/project/torus-sdk-js/node_modules/@toruslabs/fetch-node-details/dist/fetchNodeDetails.cjs.js:8:104448)
    at r (/Users/user/Workplace/project/torus-sdk-js/node_modules/@toruslabs/fetch-node-details/dist/fetchNodeDetails.cjs.js:1:124)
```
**To Reproduce**

Make sure `node` is installed

1. Run `yarn add @toruslabs/torus-embed`
2. Run `yarn add @babel/runtime`
3. Run `node`
4. Run `const Torus = require("@toruslabs/torus-embed");`

**Expected behavior**
`torus-embed` is successfully included 

**Desktop (please complete the following information):**
 - OS: macOS Catalina(Version 10.15.4)
 - Node: v10.18.0
 - package.json: 
```
{
  "dependencies": {
    "@babel/runtime": "^7.9.2",
    "@toruslabs/torus-embed": "^1.3.0"
  }
}
```

**Comment by tetratorus** [comment]
our code can only be run in the browser, a this is a plugin that works only on the client side.

the reason for this is that we need access to browser APIs like window.open and fetch to trigger user logins and confirmation, most of the APIs for torus-embed are not really usable until the user is logged in.

**Comment by vhurryharry** [comment]
@tetratorus I am using your library in the chrome browser but getting this error.
In order to add Torus login to Web3Modal, I did like below.
```
import Torus from "@toruslabs/torus-embed";

const providerOptions = {
    torus: {
            package: Torus, // required
            options: {
                networkParams: {
                    host: "https://localhost:8545", // optional
                    chainId: 1337, // optional
                    networkId: 1337 // optional
                },
                config: {
                    buildEnv: "development" // optional
                }
            }
        }
    }
}

const web3Modal = new Web3Modal({
        network,
        cacheProvider,
        providerOptions
});
await web3Modal.connect();
```

But getting this error - ReferenceError: btoa is not defined.
I don't think that this error is from the Web3Modal coz the error location is from `node_modules/@toruslabs/torus-embed/dist/torus.cjs.js`.
