### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by ZhangPeibin** [torusresearch/torus-embed#359]
Version: 1.12.1

Once F5 to refresh page , this error shows!

eferenceError: window is not defined
    at Object.<anonymous> (E:\IPFSpace\node_modules\@toruslabs\torus-embed\dist\torus.cjs.js:18:57755)
    at Object.module.exports (E:\IPFSpace\node_modules\@toruslabs\torus-embed\dist\torus.cjs.js:18:57828)
    at r (E:\IPFSpace\node_modules\@toruslabs\torus-embed\dist\torus.cjs.js:1:124)
    at Object.module.exports (E:\IPFSpace\node_modules\@toruslabs\torus-embed\dist\torus.cjs.js:18:52312)
    at r (E:\IPFSpace\node_modules\@toruslabs\torus-embed\dist\torus.cjs.js:1:124)
    at Object.module.exports (E:\IPFSpace\node_modules\@toruslabs\torus-embed\dist\torus.cjs.js:18:21065)
    at r (E:\IPFSpace\node_modules\@toruslabs\torus-embed\dist\torus.cjs.js:1:124)
    at Object.module.exports (E:\IPFSpace\node_modules\@toruslabs\torus-embed\dist\torus.cjs.js:18:19948)
    at r (E:\IPFSpace\node_modules\@toruslabs\torus-embed\dist\torus.cjs.js:1:124)
    at Object.module.exports (E:\IPFSpace\node_modules\@toruslabs\torus-embed\dist\torus.cjs.js:18:5701)
    at r (E:\IPFSpace\node_modules\@toruslabs\torus-embed\dist\torus.cjs.js:1:124)
    at Object.e.exports (E:\IPFSpace\node_modules\@toruslabs\torus-embed\dist\torus.cjs.js:16:252566)
    at r (E:\IPFSpace\node_modules\@toruslabs\torus-embed\dist\torus.cjs.js:16:251671)
    at Module.<anonymous> (E:\IPFSpace\node_modules\@toruslabs\torus-embed\dist\torus.cjs.js:16:254176)
    at r (E:\IPFSpace\node_modules\@toruslabs\torus-embed\dist\torus.cjs.js:16:251671)
    at e.exports (E:\IPFSpace\node_modules\@toruslabs\torus-embed\dist\torus.cjs.js:16:252470)

**Comment by chaitanyapotti** [comment]
Can you provide a minimal reproducible example?

**Comment by integrityteamdev** [comment]
Hello I am still experiencing this issue on 1.13.7

"react": "17.0.2",
 "next": "^11.1.2",
